### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-tests#1]
Tom, can you check permissions on this repo please... I cant create branches, push etc... Cheers

**Comment by TomWaterat** [comment]
I gave you Admin rites.. Did you get an email with this link? [https://github.com/NSW-OEH-EMS-KST/grid-garage-tests/invitations](https://github.com/NSW-OEH-EMS-KST/grid-garage-tests/invitations)

**Comment by byezy** [comment]
not yet... what email account?

**Comment by TomWaterat** [comment]
I've changed the permission.. did you receive an invite? Can you just follow that link?

**Comment by byezy** [comment]
Ta
